export const ROLES = {
  CUSTOMER: "CUSTOMER",
  DELIVERY_PARTNER: "DELIVERY_PARTNER",
  RESTAURANT_OWNER: "RESTAURANT_OWNER",
  RESTAURANT_TEAM: "RESTAURANT_TEAM",
  MANAGEMENT: "MANAGEMENT",
  BUSINESS: "BUSINESS",
};
